# Generated by Django 3.1.7 on 2021-03-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_api', '0004_auto_20210306_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognizedobject',
            name='image',
        ),
    ]
