# Generated by Django 3.1.7 on 2021-03-06 14:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_api', '0005_remove_recognizedobject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedobject',
            name='anothername',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recognizedobject',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddmivk4av/image/upload/v1615040123/diplomawork/not_found.jpg', max_length=255, verbose_name='image'),
        ),
    ]
