# Generated by Django 3.1.7 on 2021-03-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_api', '0011_auto_20210308_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizedobject',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
